# config.py
# Global settings and magic numbers for Succi Solace

# --- PLAYER PHYSICS ---
PLAYER_SPEED_WALK = 180.0
PLAYER_SPEED_RUN = 320.0
PLAYER_JUMP_IMPULSE = -800.0
PLAYER_GRAVITY = 1500.0

# --- PLAYER STATS ---
PLAYER_STARTING_HEALTH = 1
PLAYER_INVULNERABLE_DURATION = 1000  # in milliseconds

# --- PLAYER RENDERING ---
PLAYER_BASE_SCALE = 0.25
PLAYER_ATTACK_Y_OFFSET = 230
PLAYER_ATTACK_X_SHIFT = 200
DEFAULT_ANIM_DELAY = 120